### ISSUE TITLE
提醒一下有个变量重复命名错误

### ISSUE THREAD

**Issue by qdyx** [Sophia-fez/Standford-CS193p-2020Spring-SwiftUI#1]
https://github.com/Sophia-fez/Standford-CS193p-2020Spring-SwiftUI/blob/f5ec820684cf9939b1fb71dfc2d2a38f622627a6/06.Animation/MyDemo_6_Memorize/MemoryGame.swift#L90-L96

命名重复了 换一个即可： 视频重的命名
var bonusRemaing: Double{
            (bonusTimeLimit > 0 && bonusTimeRemaining > 0) ? bonusTimeRemaining / bonusTimeLimit : 0
 }

**Comment by Sophia-fez** [comment]
已修改
```
 		var bonusTimeRemaining: TimeInterval{ 
 			max(0, bonusTimeLimit - faceUpTime) 
 		} 
 		// percentage of the bonus time remaining 
 		var bonusRemaining: Double{ 
 			(bonusTimeLimit > 0 && bonusTimeRemaining > 0) ? bonusTimeRemaining / bonusTimeLimit : 0 
 		} 
```
是bonusRemaining，你也敲错了😂
